spring.application.name=spring-batch-sample

spring.datasource.jdbcUrl=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver

spring.batch.jdbc.initialize-schema=always

logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE
logging.level.org.springframework.batch.core.repository.support.SimpleJdbcJobRepository=INFO
logging.level.org.springframework.batch.core.repository.dao=INFO