spring.application.name=spring-batch-sample

spring.main.allow-bean-definition-overriding=true

spring.business.datasource.jdbcUrl=jdbc:h2:mem:testdb
spring.business.datasouece.username=sa
spring.business.datasource.password=
spring.business.datasource.driverClassName=org.h2.Driver
