spring.application.name=spring-batch-sample

spring.datasource.jdbcUrl=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver

spring.batch.jdbc.initialize-schema=always

logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace
logging.level.org.hibernate.type.EnumType=trace
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true